-- TABLAS TEMPORALES
-- NIVEL DE SESIÓN
-- NIVEL DE TRANSACCIÓN
-- SINTAXIS
-- CREATE [TEMPORARY|TEMP] TABLE NOMBRE_TABLA
-- (COLUMNAS)
-- [ON COMMIT (PRESERVE ROWS | DELETE ROWS | DROP)]
-- PRESERVE ROWS y DELETE ROWS SON PARA INDICAR QUE LAS TABLAS SON TEMPORALES EN UNA SESIÓN
-- DROP INDICA QUE LA TABLA ES TEMPORAL EN UNA TRANSACCIÓN
-- SINTAXIS DE CONSULTA
-- CREATE [TEMPORARY|TEMP] TABLE NOMBRE_TABLA
-- [ON COMMIT (PRESERVE ROWS | DELETE ROWS | DROP)]
-- AS
-- QUERY
-- [WITH [NO] DATA]
CREATE TEMPORARY TABLE temporal1 (turno_id INT, turno_data VARCHAR(255)) ON COMMIT DELETE ROWS;

CREATE TEMPORARY TABLE temporal2 (turno_id INT, turno_data VARCHAR(255)) ON COMMIT PRESERVE ROWS;

INSERT INTO
    temporal2 (turno_id, turno_data)
VALUES
    (1, 'dato 1 temporal 1');

INSERT INTO
    temporal2 (turno_id, turno_data)
VALUES
    (2, 'dato 2 temporal 1');

-- COMMIT;
-- CREAR UNA TABLA TEMPORAL CON TODAS LAS TAREAS CON PRIORIDAD MEDIA Y QUE MUESTRE EL NOMBRE DE LA PRIORIDAD Y QUE SEA DENTRO DE UNA TRANSACCIÓN
-- Ejemplo:
-- CREATE TEMP TABLE tareas_media AS
-- SELECT t.*, p.nombre AS prioridad_nombre
-- FROM tareas t
-- JOIN prioridades p ON t.pid = p.pid
-- WHERE p.nombre = 'media'
-- ON COMMIT DROP;
